set(_CATKIN_CURRENT_PACKAGE "ARO_summit")
set(ARO_summit_VERSION "0.0.0")
set(ARO_summit_MAINTAINER "oj <oj@todo.todo>")
set(ARO_summit_PACKAGE_FORMAT "2")
set(ARO_summit_BUILD_DEPENDS )
set(ARO_summit_BUILD_EXPORT_DEPENDS )
set(ARO_summit_BUILDTOOL_DEPENDS "catkin")
set(ARO_summit_BUILDTOOL_EXPORT_DEPENDS )
set(ARO_summit_EXEC_DEPENDS )
set(ARO_summit_RUN_DEPENDS )
set(ARO_summit_TEST_DEPENDS )
set(ARO_summit_DOC_DEPENDS )
set(ARO_summit_URL_WEBSITE "")
set(ARO_summit_URL_BUGTRACKER "")
set(ARO_summit_URL_REPOSITORY "")
set(ARO_summit_DEPRECATED "")